name: flow_project
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  auto_route: ^5.0.2
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  deps: ^0.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^2.1.1
  font_awesome_flutter: ^10.2.1
  freezed_annotation: ^2.2.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  json_annotation: ^4.7.0
  json_path: ^0.4.2
  page_transition: ^2.0.9
  pretty_dio_logger: ^1.1.1
  salomon_bottom_bar: ^3.3.1
  shared_preferences: ^2.0.15
  timeago: ^3.3.0
  url_launcher: ^6.1.6

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/env/
    - assets/env/.env
    - assets/
    - assets/images/

flutter_gen:
  output: lib/gen/
  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml
